name: Update Nodes
on:
  schedule:
    - cron: '0 */6 * * *' # 每6小时运行一次
  workflow_dispatch:      # 允许你手动点按钮运行

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # 赋予写入权限
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: python main.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add nodes.txt nodes.yaml
          git commit -m "自动更新节点 $(date)" || exit 0
          git push
